# site settings
title: The Mana Vibe
subtitle: A place to jig out.
email: theferrellcouple@gmail.com
description: The jig-jigga-ist jig-jiggaaaaa, hoy jigga.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: The Ferrell Couple
street_address:
city:
state:
zip_code:
country:
phone:

# Call to action
cta_title: Our mission
cta_button_text: Let's go!
cta_body: |
    Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
